### ISSUE TITLE
Flickering issue in ubuntu 18.04

### ISSUE THREAD

**Issue by raghwendra2022** [albfan/miraclecast#447] opened 2022-07-28 10:26 UTC
When running miraclecast for some time , screen starts flickering. Need some help on this

**Comment by albfan** [comment] 2022-07-28 14:17
Probably a screencast or logs for support can be helpful

**Comment by raghwendra2022** [comment] 2022-07-29 06:32
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/107671658/181697379-fb4accf1-14cf-463f-863b-1093f3e30024.png)

Please see the attached screenshot

**Comment by albfan** [comment] 2022-07-29 10:01
screencast means video (is problematic here as github do not allow mp4 or webm) from that flickering we cannot see any flickering

log for support is documented here: https://github.com/albfan/miraclecast/wiki/FAQ#log-for-support

**Comment by raghwendra2022** [comment] 2022-07-29 12:14
https://user-images.githubusercontent.com/107671658/181756085-a7816028-8150-4fa0-aafd-6e41408ff9e0.mp4

Please review the attached video

**Comment by albfan** [comment] 2022-07-29 12:58
Looks like lag, collect logs to check if there's something obvious. What's the environment for source and target? Windows to ubuntu? See you might need to configure some extra parameters windows uses: https://github.com/albfan/miraclecast/wiki/FAQ#microsoft-os-support

**Comment by raghwendra2022** [comment] 2022-07-29 16:09
Yes it is windows to Ubuntu. Same issue is with Android to Ubuntu

**Comment by albfan** [comment] 2022-07-29 19:57
Collect logs to review what's going on

**Comment by raghwendra2022** [comment] 2022-08-01 06:56
[MiracleLogs.zip](https://github.com/albfan/miraclecast/files/9231622/MiracleLogs.zip)

Please find the attached logs

**Comment by raghwendra2022** [comment] 2022-08-01 16:16
Did you get the chance to review the logs

**Comment by albfan** [comment] 2022-08-02 06:17
I think this is related with:

>  rtpjitterbuffer rtpjitterbuffer.c:570:calculate_skew: delta - skew: 0:26:19.981801335 too big, reset skew

but can you attach logs using android (remove microsoft  config) and let's compare logs

**Comment by raghwendra2022** [comment] 2022-08-02 06:46
Ok sure, Thanks

**Comment by raghwendra2022** [comment] 2022-08-08 04:51
[Android Device Miracast Logs.zip](https://github.com/albfan/miraclecast/files/9278801/Android.Device.Miracast.Logs.zip)

Please find the logs for Android.

**Comment by raghwendra2022** [comment] 2022-08-14 05:45
Any finding that will help us to resolve this issue.

**Comment by albfan** [comment] 2022-08-28 10:09
For me still this is something to address at gstreamer.

> rtpjitterbuffer rtpjitterbuffer.c:570:calculate_skew: delta - skew: 0:06:46.999929427 too big, reset skew

You can modify parameters from rtpjitterbuffer

https://gstreamer.freedesktop.org/documentation/rtpmanager/rtpjitterbuffer.html?gi-language=c

here we set a latency of 100 (default is 200)

See you can use vlc as player to check if provided player is not smart enough:

https://github.com/albfan/miraclecast/wiki/miracle-sinkctl#external-player

You can use this examples to run a rtp server and test what gstreamer best reproduces it:

https://stackoverflow.com/questions/13154983/gstreamer-rtp-stream-to-vlc

**Comment by raghwendra2022** [comment] 2022-09-14 05:05
Hi, one quick question is the library has dependency on any Specific Driver

**Comment by raghwendra2022** [comment] 2022-09-14 10:37
Any more input will be helpful. It is working fine on One laptop but not working on another machine. We are using ubuntu 18.04

**Comment by albfan** [comment] 2022-09-14 14:28
You're basically moving the problem in your laptop to a problem in miraclecast, just because its maintainer replies to open issues.

I'm unsure what causes this problem, have laptops same specs? it can be (faulty RAM, overheating, different packages installed on your OS) I really don't know.

Start by comparing logs from correct laptop with faulty laptop.

Expecting other to identify what's different from your own environment is really complex.

Closing as there's no actionable task to fix here, we can reopen if you provide any info to review

**Closed by albfan** 2022-09-14 14:28 UTC
