### ISSUE TITLE
check pkg-config is installed

### ISSUE THREAD

**Issue by awlnx** [albfan/miraclecast#120] opened 2016-09-05 02:33 UTC
Debian testing
systemctl --verson prints 230 as version number

**Comment by albfan** [comment] 2016-09-05 05:45
Can you post here the autogen.sh command line input and its output and the configure command line input and its output.

Let's see what's happening

**Comment by albfan** [comment] 2016-09-07 12:24
Any progress? Can I close this?

**Comment by emmandyar** [comment] 2016-10-25 22:55
Hi! I was trying to build it and face the same issue(not sure if the cause is the same, though), running on ubuntu 16.10, systemd 231
autogen.sh:
```
andres@Keiko ~/miraclecast $ ./autogen.sh 
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: linking file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: linking file 'm4/libtool.m4'
libtoolize: linking file 'm4/ltoptions.m4'
libtoolize: linking file 'm4/ltsugar.m4'
libtoolize: linking file 'm4/ltversion.m4'
libtoolize: linking file 'm4/lt~obsolete.m4'
configure.ac:17: installing 'build-aux/compile'
configure.ac:21: installing 'build-aux/missing'
src/Makefile.am: installing 'build-aux/depcomp'

----------------------------------------------------------------
Initialized build system. For a common configuration please run:
----------------------------------------------------------------

./configure CFLAGS='-g -O0 -ftrapv' --sysconfdir=/etc --localstatedir=/var --libdir=/usr/lib 

or run ./autogen.sh with param:

- c: compilation
- g: debugging
- a: pure/const warning
- l: clang build
- s: scan-build reporting

```

configure:
```
andres@Keiko ~/miraclecast/build $ ../configure --prefix=/usr/local
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking dependency style of gcc... gcc3
checking whether make supports nested variables... (cached) yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking for gcc option to accept ISO C99... none needed
checking for ar... ar
checking the archiver (ar) interface... ar
checking for a sed that does not truncate output... /bin/sed
checking whether ln -s works... yes
checking for grep that handles long lines and -e... (cached) /bin/grep
checking for gawk... (cached) mawk
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for cos in -lm... yes
../configure: line 13639: syntax error near unexpected token `DEPS,'
../configure: line 13639: `PKG_CHECK_MODULES(DEPS, libudev libsystemd > 219)'

```

**Comment by albfan** [comment] 2016-10-26 05:34
It works for me, with exactly the same parameters as you. I have a virtual machine with ubuntu 16.10. Let me  check there and tell you something.

**Comment by nicoruy** [comment] 2016-11-12 22:50
The issue seems to be related to the macro PKG_CHECK_MODULES not working with autotools.
This aritcle helped me solve the same issue:
https://coffeecode.net/archives/208-PKG_CHECK_MODULES-syntax-error-near-unexpected-token-DEPS,.html

After installing pkg-config and running autogen.sh again, configure run without issues.

**Comment by albfan** [comment] 2016-11-13 11:23
That's interesting. I suppose pkg-config comes with `build-essential` and `autotools` packages. But it is an isolate package.

http://packages.ubuntu.com/yakkety/pkg-config

so, you need to install pkgconf I guess, right?

Well, best way to close this issue is to check for pkg-config existence. See cmake set a variable about pkg-config existence on environment:

https://cmake.org/cmake/help/v3.0/module/FindPkgConfig.html

So look for `PKG_CONFIG_FOUND` is a way to solve this issue for others

Here is an example I have found to use it:

https://github.com/OpenMandrivaAssociation/avidemux-restricted/blob/17e3a29285c50400b1469269dd37e3a79ed8b1e4/avidemux-cmake-2.8.8.patch#L7

As doc says

https://cmake.org/cmake/help/v3.0/command/message.html

message fatal will stop configuration and compilation.

Can you provide a PR with all this?

Add new stuff behind this line

https://github.com/albfan/miraclecast/blob/master/CMakeLists.txt#L23

**Comment by albfan** [comment] 2017-04-18 04:16
If someone interested in provide this check I'm open to accept it. But seems like check for gcc

**Closed by albfan** 2017-04-18 04:16 UTC

**Comment by hanslovsky** [comment] 2018-12-28 13:21
FYI, for anyone running into this on Arch Linux, the package that you need to install is `pkgconf`.

**Comment by Hurricos** [comment] 2019-04-03 21:09
I've created a merge request for a patch which resolves getting errors when `pkg-config` is not available. Rather than create a hard dependency on `pkg-config`, we can just use it if we have it; if we don't, then we're simply not checking that necessary packages exist, and we'll fail at build time if they're not present.

**Comment by albfan** [comment] 2019-04-03 23:13
@Hurricos thanks for the PR. Is merged now. Anyway to fix this it should be implemented on cmake, and there's too meson.

**Comment by Hurricos** [comment] 2019-04-04 00:06
I'll see if I can find time to do those as well.
