### ISSUE TITLE
can not connect

### ISSUE THREAD

**Issue by zglx2008** [albfan/miraclecast#32] opened 2015-07-18 06:53 UTC
Hi Alberto,

I have all installed and running in a ubuntu15.04 machine.

The netcard we use is RTL8188, and we started the wpa in RTL8188 with ./wpa_supplicant -i wlan0 -Dwext -c wpa.conf ,then miracle-wifid & and returns a value, the next miracle-sinkctl and only shows [miraclectl] #. my device can't  find and connect.
Does miraclecast have logs? where is the log? How can I see the logs?What can I do to find what is wrong?

Thanks again.

**Comment by albfan** [comment] 2015-07-18 10:00
see #31. `--log-level` is avaliable on every command

Have you test against [test-wifi-capabilities.sh](https://github.com/albfan/miraclecast/blob/master/res/test-wifi-capabilities.sh)

please read README.md for prerequisites.

**Comment by zglx2008** [comment] 2015-07-21 12:44
Thanks Alverto:
 I have some trouble in miraclecast, 
1.$res/kill-wpa.sh, 
2.$ wpa_supplicant -dd -B -iwlp3s0 -Dnl80211 -c wpa.conf
3.$miracle-wifid &
when use the command miracle-wifid, it also contains the wpa_supplicant in the function supplicant_run, is it conflict to step 2.Now I have three wpa_supplicant commands, fisrt is in the RTL8188 which support the p2p, second is in the ubuntu system, the last is in our miraclecast program,what's the difference between them.

The error I met is "cannot attach to global wpas interface of wlan1 "in the function supplicant_global_attach_fn, I don't know why. and I see the msg->raw is unknown command.
The ctrl_path in the function wpas_new is /run/miracle/wifi, but when I use command $/home/wpa_supplicant -dd -B -iwlp3s0 -Dnl80211 -c wpa.conf, the path is in the /var/run/wpa_supplicant, should the two path keep the same.

**Comment by albfan** [comment] 2015-07-21 13:16
actual connection must be killed before start miraclecast. You can do by yourself or use the scripts in res directory:
[kill-wpa.sh:11](https://github.com/albfan/miraclecast/blob/0921f6ee3204d18404bef4fc63ee9167b793d0f9/res/kill-wpa.sh#L11)
[miracle-wifi.sh:3](https://github.com/albfan/miraclecast/blob/0921f6ee3204d18404bef4fc63ee9167b793d0f9/res/miracle-wifi.sh#L3)

You shouldn't been able to navigate on internet during correct config for miraclecast.

If wpa_supplicant ends miraclecast try to set it up again:
[wifid-supplicant.c:2437](https://github.com/albfan/miraclecast/blob/0921f6ee3204d18404bef4fc63ee9167b793d0f9/src/wifi/wifid-supplicant.c#L2437)
kill it and see what miracle-wifid does

The only connection you should see is 
[miracle-wifi.sh:54](https://github.com/albfan/miraclecast/blob/0921f6ee3204d18404bef4fc63ee9167b793d0f9/res/miracle-wifi.sh#L54)

use the wifi tester (as said in prior message) and debug around [wifid-supplicant.c:2429](https://github.com/albfan/miraclecast/blob/0921f6ee3204d18404bef4fc63ee9167b793d0f9/src/wifi/wifid-supplicant.c#L2429) to understand where is your problem

**Comment by zglx2008** [comment] 2015-07-22 10:28
Thanks Alberto:
I have arrived $miracle-sinkctl and the screen shows [miraclecast]:[add] link 4, [add]link 5, use command "list" then shows 0 peers and 2 links listed.The device can not find the net when use WLAN direct.

when run the miracle-wifid --log-level=7 ,it shows "wpa_supplicant does not support wifi-display in function supplicant_status_fn". when I try to write "wfd_tcpport=554,wfd_device_type=1" into wpa.conf, error happens when run /res/miracle-wifid.sh

what is the problem??

**Comment by albfan** [comment] 2015-07-22 11:14
> when run the miracle-wifid --log-level=7 ,it shows "wpa_supplicant does not support wifi-display in function supplicant_status_fn"

Show the output from [test-wifi-capabilities.sh](https://github.com/albfan/miraclecast/blob/master/res/test-wifi-capabilities.sh)

miraclecast shows you possible devices to use, but you must select it with

    > run 4

or 

    > run 5

Is all in [README.md](https://github.com/albfan/miraclecast/blame/master/README.md#L100)

**Comment by zglx2008** [comment] 2015-07-22 12:06
Thanks Alberto:
when run the  test-wifi-capabilities.sh,the output is :
root@avonaco-Vostro-270:~/avonaco/miraclecast-master-cp/res# ./test-wifi-capabilities.sh 
Choose wireless device:
1) wlan0
2) wlan1
3) exit
device: 2
wlan1 supports P2P

root@avonaco-Vostro-270:~# miracle-sinkctl 
[ADD] Link: 5
[ADD] Link: 4
[miraclectl] # run 5
now running on link 5
[miraclectl] # list
  LINK PEER-ID                  FRIENDLY-NAME                  CONNECTED 
     5 d2:22:be:dd:ba:fb@5      Galaxy Note3                   no        
 1 peers and 2 links listed.
but the Note3 can not find it and can not connect through wlan direct.
And the following messges repeated in the log,
DEBUG: supplicant: *************supplicant_event,name CTRL-EVENT-SCAN-STARTED
 (supplicant_event() in ../../../src/wifi/wifid-supplicant.c:1400)
DEBUG: supplicant: *************supplicant_event,name CTRL-EVENT-SCAN-STARTED
 (supplicant_event() in ../../../src/wifi/wifid-supplicant.c:1400)

**Comment by zglx2008** [comment] 2015-07-23 06:46
When run $ /res/miracle-wifid ,it outputs a message:
"dbus:wpa_dbus_object_properties: failed to get object properties:none" 
"dbus:Failed to construct signal"
does it affect the function??
Thanks!

**Comment by albfan** [comment] 2015-07-23 12:17
See miraclecast is a bunch of hacks among isolate executables

whether you use `miracle-sinkctl` or `miracle-wifictl` it starts appropriately miracle-dhcp:

[wifid-supplicant.c:389](https://github.com/albfan/miraclecast/blob/0921f6ee3204d18404bef4fc63ee9167b793d0f9/src/wifi/wifid-supplicant.c#L389)

[wifid-supplicant.c:451](https://github.com/albfan/miraclecast/blob/0921f6ee3204d18404bef4fc63ee9167b793d0f9/src/wifi/wifid-supplicant.c#L451)

**Comment by albfan** [comment] 2015-07-26 07:45
Can I close this issue, any progress?

**Comment by zglx2008** [comment] 2015-07-27 09:30
Tks Alberto:
[miraclectl] # run 8
now running on link 8
[miraclectl] # list
LINK INTERFACE FRIENDLY-NAME
9 wlan0 cassail-Vostro-270
8 p2p0 cassail-Vostro-270
LINK PEER-ID FRIENDLY-NAME CONNECTED
0 peers and 2 links listed.
[ADD] Peer: d2:22:be:dd:ba:fb@8 (here use my phone to mirror, My pc did recognize my phone)
[miraclectl] # list
LINK INTERFACE FRIENDLY-NAME
9 wlan0 cassail-Vostro-270
8 p2p0 cassail-Vostro-270
LINK PEER-ID          FRIENDLY-NAME CONNECTED 
8 d2:22:be:dd:ba:fb@8 Galaxy Note3           no
1 peers and 2 links listed.

but when I try to use my phone to connect, it does not response at all, still can not connect. How could I do next?

**Comment by albfan** [comment] 2015-07-28 18:38
You could give a hand on #35. It is not fixed yet.

**Closed** 2015-07-29 18:39 UTC

**Comment by lyfanglim** [comment] 2015-08-13 08:03
HI, I am a newbie in wifi-direct and MIraclecast. I met the same problem where I cant list link & peers but my Galaxy Note 3 cannot connect and require pin numbers from my side which I didn't set any pin numbers. What I can do?or any pin number set in default in any script or config file? I am not really understand why this is related to #35 since I use systemd with version 221 (which is >=219 version recommended). Thanks for your advice on this.

**Comment by albfan** [comment] 2015-08-13 08:15
If pbc method fail now config uses next method configured.

You can see pin on `miracle-sinkctl` output. Use `--log-level` option if it is not show by default

If you don't want this behaviour remove alternative connection methods from wpa.conf

#35 points out interface callback changes. Maybe not all are detected so people on the edge should check there's no more undetected interface changes.

**Comment by lyfanglim** [comment] 2015-08-13 09:15
HI, I didn't see any pin output on miracle-sinkctl. So I use --log level to check it turns out 
 miracle-wifid --log-level 7
INFO: miracle-wifid - revision some-rev-TODO-xyz Aug  6 2015 13:40:49
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -17 (manager_dbus_connect() in ../../../src/wifi/wifid-dbus.c:898)
DEBUG: exiting.. (main() in ../../../src/wifi/wifid.c:551)
which is related to the dbus connect issue #20 . But I had copied the dbus policy file ( to /etc/dbus-1/system.d) why this dbus connect issue is still there? but if I didn't run --log-level and I still managed to run miracle-wifid and miracle-sinkctl

I also tried to edit the wpa.conf ( config_methods=pbc ) but it still requires pin no. Have no idea what is happening..

**Comment by albfan** [comment] 2015-08-13 21:53
See is `miracle-sinkctl` which shows the pin with `--log-level`

About `wpa.conf` see it is installed

https://github.com/albfan/miraclecast/blob/master/res/Makefile.am#L2

and now is recommended just to kill wpa_supplicant and let `miracle-wifid` start it.

**Comment by lyfanglim** [comment] 2015-08-14 03:08
HI, I managed to display out the pin number on miracle-sinkctl after I start miracle-wifid without running wpa_supplicant. Thanks~
But another problem comes out after I key in the pin no from what I get in miracle-sinkctl, it is still failed to connect Note3 with my SUT after key in pin no and go neg. Error is popped-out 
error: supplicant HUP on dhcp-comm socket on p2p-wlp0s20u2-0 (supplicant_group_com_fn() in ../../../src/wifi/wifid-supplicant.c:246)

Is another problem that dhcp to cause failure?

**Comment by lyfanglim** [comment] 2015-08-17 02:28
Attached what I seen in miracle-sinkctl:
[ADD] Peer: 4a:5a:3f:11:4a:3f@12
[PROV] Peer 4a:5a:3f:11:4a:3f@12 Type: display PIN:80787839
[GO NEG] Peer 4a:5a:3f:11:4a:3f@12 Type: display  PIN:8078783
After this, then in log-level it just shows error: supplicant HUP on dhcp-comm socket on p2p-wlp0s20u2-0 (supplicant_group_com_fn() in ../../../src/wifi/wifid-supplicant.c:246)

**Comment by albfan** [comment] 2015-08-17 07:37
I will take a look and tell you something. Are you enable to debug that code?

**Comment by lyfanglim** [comment] 2015-08-17 08:03
HI, nope..not able to...and today I cannot reproduce the same error with dhcp_comm_socket.
So I tried again..using command wpa_supplicant -u ( which enable dbus) error is different again. It shows that after P2P-GO-NEG-REQ 4a:5a:3f:11:4a:3f@12, 
The P2PS-PROV-DONE 4a:5a:3f:11:4a:3f@12 status=11 adv_id=0 adv_mac=00:00:00:00:00:00 session=0 mac=00:00:00:00:00:00
P2P-DEVICE-LOST p2p_dev_addr=4a:5a:3f:11:4a:3f@12
dbus:unregistered peer object '/fi/w1/wpa_supplicant/Interfaces/1/Peers/4a:5a:3f:11:4a:3f@12
then note3 phone shows failed to connect via screen sharing

**Comment by lyfanglim** [comment] 2015-08-19 10:53
Hi, I am still debug what is causing the hang up on dhcp-comm-socket. What I did was trying to check wpa_cli & wpa_supplicant -u.
In wpa_cli, it was showing it is trying to associate and authenticate with other network with SSID. 
In wpa_supplicant -u, it shows no network configuration found for the current AP.

I have questions about the AP here, is it p2p is not access to AP?
After the GO -NEG -REQ, supplicant will create a new group and set dongle as client & set STA MAC for Note3 device from none to 4a:5a:3f:11:4a:3f@12. but I do not know how to check the GO at here. 

Still struggling what causing this error or is it due to network problem?

**Comment by lyfanglim** [comment] 2015-08-20 09:05
Hi Alberto, any good news from your side? I have no idea what is causing this dhcp_comm_socket hang up error..Do you know any way to check is the dongle or device act as server or client ? I suspect  there is no GO so that's why it cannot go through to send request from GO to client.
Below is the error in my log file,
set STA-MAC for  4a:5a:3f:11:4a:3f (device)
supplicant is creating a new group for p2p-wlp0s20u2-1 (dongle)
So client is TP-link dongle & CE device is station. Then no GO??

**Comment by albfan** [comment] 2015-08-21 10:46
I like this tutorial for its simplicity to create Wifi-direct conections

- [Wifi direct part1](https://thangamaniarun.wordpress.com/2013/03/03/how-to-use-wi-fi-direct-on-androidubuntu-part1/)
- [Wifi direct part2](https://thangamaniarun.wordpress.com/2013/04/07/how-to-setup-wi-fi-direct-on-androidubuntu-terminal-part2/)
- [Wifi direct part3](https://thangamaniarun.wordpress.com/2014/03/30/how-to-setup-wi-fi-direct-on-androidubuntu-terminal-part3/)

But I cannot find a cli on android to check where the negociation problem arises.

Try to create a complete use case: OS, systemd version, Devices, command lines, commands on miracle-*ctl to allow others to reproduce and isolate the fail step to fix it.

**Comment by albfan** [comment] 2015-08-22 10:38
I have added trace log level to see wpa raw messages

4c20c59

so

    $ sudo miracle-wifid --log-level 8

would show you all the dialog between devices.

At this point, 

    DEBUG: wpa: raw message: IFNAME=p2p-wlp3s0-0 <3>No network configuration found for the current AP

should take you to the wpa_supplicant implementation:

http://w1.fi/cgit/hostap/tree/wpa_supplicant/events.c#n195

From here, debug wpa_supplicant is the way to go.

**Comment by lyfanglim** [comment] 2015-08-24 11:51
hi Alberto, I had added trace log level that you uploaded, but for the miracle-wifid --log-level 8 still show me the dbus error:-17 . Hence I cannot show all the dialog between devices. I think the dbus error still unsolved causing the log file cannot show the debug details. Any suggestion on that?
I had encountered a problem where the wpa_supplicant -u debug file will show no network config found at my wireless connection from CE not from the wifi dongle. Confusing..

**Comment by albfan** [comment] 2015-08-24 16:42
(-17) [EEXISTS error](https://github.com/torvalds/linux/blob/master/include/uapi/asm-generic/errno-base.h#L20) is return by:

[libsystemd/sd-bus/bus-control.c:L123](https://github.com/systemd/systemd/blob/master/src/libsystemd/sd-bus/bus-control.c#L123)

Before reach that line you pass correctly:

[libsystemd/sd-bus/bus-control.c:L147](https://github.com/systemd/systemd/blob/master/src/libsystemd/sd-bus/bus-control.c#L147)

so you have correctly configured systemd and policy.

The only way to reproduce `BUS_NAME_EXISTS` error is to load twice `miracle-wifid`

    $ sudo miracle-wifid & sudo miracle-wifid --log-level 7
    [1] 8613
    INFO: miracle-wifid - revision some-rev-TODO-xyz Aug 23 2015 13:32:08
    ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -17 (manager_dbus_connect() in ../../../src/wifi/wifid-dbus.c:898)
    DEBUG: exiting.. (main() in ../../../src/wifi/wifid.c:551)
 
Check no other prior process is open before start `miracle-wifid`

    $ ps -ef | grep miracle-wifid
    root      8613  1724  0 18:35 pts/0    00:00:00 sudo miracle-wifid

and kill it:

    $ kill -9 8613

**Comment by lyfanglim** [comment] 2015-08-25 05:49
In my case after loading miracle-wifid twice it still shows error. But I don't understand after it launches miracle-wifid, the info of miracle-wifid is still showing (INFO: miracle-wifid - revision some-rev-TODO-xyz Aug  6 2015) instead of my latest date. 
May I know when launch, where the log file will be saved to?I cannot locate the log file. Or is it just showing temporary without storing anywhere? Or can I get to save/store the log file anywhere?
Below is my error:
~# miracle-wifid & miracle-wifid --log-level 8
[1] 630
INFO: miracle-wifid - revision some-rev-TODO-xyz Aug  6 2015 13:40:49
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -17 (manager_dbus_connect() in ../../../src/wifi/wifid-dbus.c:898)
DEBUG: friendly-name from local hostname: valleyisland-64 (manager_read_name() in ../../../src/wifi/wifid.c:355)
DEBUG: link: new link: wlp0s20u2 (5) (link_new() in ../../../src/wifi/wifid-link.c:71)
DEBUG: supplicant: new supplicant for wlp0s20u2 (supplicant_new() in ../../../src/wifi/wifid-supplicant.c:2077)
INFO: link: add link: wlp0s20u2
INFO: link: manage link wlp0s20u2
DEBUG: supplicant: start supplicant of wlp0s20u2 (supplicant_start() in ../../../src/wifi/wifid-supplicant.c:2558)
DEBUG: supplicant: spawn supplicant of wlp0s20u2 (supplicant_spawn() in ../../../src/wifi/wifid-supplicant.c:2406)
ERROR: supplicant: execution of wpas (/usr/bin/wpa_supplicant) not possible: No such file or directory (supplicant_spawn() in ../../../src/wifi/wifid-supplicant.c:2413)
DEBUG: supplicant: stop supplicant of wlp0s20u2 (supplicant_stop() in ../../../src/wifi/wifid-supplicant.c:2612)
DEBUG: supplicant: close supplicant of wlp0s20u2 (supplicant_close() in ../../../src/wifi/wifid-supplicant.c:2281)
ERROR: link: cannot start supplicant on wlp0s20u2 (link_set_managed() in ../../../src/wifi/wifid-link.c:149)

**Comment by albfan** [comment] 2015-08-25 06:53
Running twice is to show the error. First miracle-wifid runs correctly, and second fails because there's a previous one installed. That's your problem.

https://github.com/albfan/miraclecast/blob/master/src/wifi/wifid.c#L510

> \_\_DATE\_\_
> This macro expands to a string constant that describes the date on which the preprocessor is being run. The string constant contains eleven characters and looks like "Feb 12 1996". If the day of the month is less than 10, it is padded with a space on the left.
> If GCC cannot determine the current date, it will emit a warning message (once per compilation) and 
> __DATE__ will expand to "??? ?? ????". 
>
> \_\_TIME\_\_
> This macro expands to a string constant that describes the time at which the preprocessor is being run. The string constant contains eight characters and looks like "23:59:01".

date is a preprocessor macro, no current date will be showed.

output is flush to stdout. no log file.

Please confirm if that solves your problem

**Comment by lyfanglim** [comment] 2015-08-26 02:22
The date and time still remain the same..it seems not the factor to cause problems. In my error to launch miracle-wifid twice there is no directory, so I copy wpa_supplicant over to /usr/bin. Then I run miracle-wifid --log-level 7 it comes out a bunch of debugs & errors as seen in previous comments (). I found that this can be generated out once only if I close the terminal and rerun it, the ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -17 (manager_dbus_connect() in ../../../src/wifi/wifid-dbus.c:898) is coming out no matter how after I kill miracle-wifid.

INFO: link: add link: wlp0s20u2
INFO: link: manage link wlp0s20u2
DEBUG: supplicant: start supplicant of wlp0s20u2 (supplicant_start() in ../../../src/wifi/wifid-supplicant.c:2558)
DEBUG: supplicant: spawn supplicant of wlp0s20u2 (supplicant_spawn() in ../../../src/wifi/wifid-supplicant.c:2406)
INFO: supplicant: wpas spawned as pid:2414
DEBUG: supplicant: open supplicant of wlp0s20u2 (supplicant_open() in ../../../src/wifi/wifid-supplicant.c:2240)
DEBUG: supplicant: local p2p-address is: e8:de:27:a1:03:8d (supplicant_status_fn() in ../../../src/wifi/wifid-supplicant.c:1797)
DEBUG: link: link wlp0s20u2 started (link_supplicant_started() in ../../../src/wifi/wifid-link.c:277)
DEBUG: supplicant: send 'WFD_SUBELEM_SET 0 000600111c4400c8' to wpas on wlp0s20u2 (supplicant_set_wfd_subelements() in ../../../src/wifi/wifid                                                -supplicant.c:1965)
DEBUG: supplicant: sent P2P_FIND to wpas on wlp0s20u2 (supplicant_p2p_start_scan() in ../../../src/wifi/wifid-supplicant.c:2010)
DEBUG: supplicant: p2p-scanning now active on wlp0s20u2 (supplicant_p2p_find_fn() in ../../../src/wifi/wifid-supplicant.c:1891)
DEBUG: peer: new peer: 4a:5a:3f:06:0c:8e @ wlp0s20u2 (peer_new() in ../../../src/wifi/wifid-peer.c:52)
INFO: peer: add peer: 4a:5a:3f:06:0c:8e
DEBUG: peer: peer 4a:5a:3f:06:0c:8e @ wlp0s20u2 started (peer_supplicant_started() in ../../../src/wifi/wifid-peer.c:162)
DEBUG: supplicant: requesting data for new peer 4a:5a:3f:06:0c:8e (supplicant_event_p2p_device_found() in ../../../src/wifi/wifid-supplicant.c                                                :957)
DEBUG: supplicant: GO Negotiation Request from 4a:5a:3f:06:0c:8e (supplicant_event_p2p_go_neg_request() in ../../../src/wifi/wifid-supplicant.                                                c:1060)
DEBUG: supplicant: connect to 4a:5a:3f:06:0c:8e via display/66252627 (supplicant_peer_connect() in ../../../src/wifi/wifid-supplicant.c:734)
DEBUG: supplicant: p2p-scanning stopped on wlp0s20u2 (supplicant_event_p2p_find_stopped() in ../../../src/wifi/wifid-supplicant.c:899)
DEBUG: supplicant: set STA-MAC for 4a:5a:3f:06:0c:8e from <none> to 4a:5a:3f:06:8c:8e (via GO-NEG-SUCCESS) (supplicant_event_p2p_go_neg_succes                                                s() in ../../../src/wifi/wifid-supplicant.c:1190)
DEBUG: supplicant: new group: p2p-wlp0s20u2-0 (supplicant_group_new() in ../../../src/wifi/wifid-supplicant.c:484)
DEBUG: supplicant: start remote group on new group p2p-wlp0s20u2-0 as client/0 (supplicant_event_p2p_group_started() in ../../../src/wifi/wifi                                                d-supplicant.c:1245)
ERROR: supplicant: HUP on dhcp-comm socket on p2p-wlp0s20u2-0 (supplicant_group_comm_fn() in ../../../src/wifi/wifid-supplicant.c:246)
DEBUG: supplicant: free group p2p-wlp0s20u2-0 (supplicant_group_free() in ../../../src/wifi/wifid-supplicant.c:173)
DEBUG: supplicant: killing DHCP-process pid:2434.. (supplicant_group_free() in ../../../src/wifi/wifid-supplicant.c:197)
DEBUG: caught SIGCHLD for 2434, reaping child (manager_signal_fn() in ../../../src/wifi/wifid.c:163)
DEBUG: supplicant: stray P2P-GROUP-REMOVED: <3>P2P-GROUP-REMOVED p2p-wlp0s20u2-0 client reason=REQUESTED (supplicant_event_p2p_group_removed()                                                 in ../../../src/wifi/wifid-supplicant.c:1277)

it seems to create the group miracle-sinkctl will always make p2p_group removed and the reason= requested. Not sure why it request to remove group.

**Comment by albfan** [comment] 2015-08-26 18:50
Date and time are generated at compile time. That was only for your information.

You have a `--wpa-bindir` to point to wpa_supplicant directory, do not copy any executable.

Don't launch miracle-wifid twice, it is just to show the origin of

    ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -17 (manager_dbus_connect() in ../../../src/wifi/wifid-dbus.c:898)

I'm working to show more info on group formation, since it feels buggy on some devices. Please confirm you have solve all those problems to focus on devices handshake problems.

**Comment by lyfanglim** [comment] 2015-08-27 07:28
I see..then I will run back the method to direct the wpa_supplicant directory. Thanks Alberto..=)
I will try to solve at my end also...but the handshake problem not sure is related to network problem or not...
