### ISSUE TITLE
wifi-display, P2P wpa_supplicant or driver does not support

### ISSUE THREAD

**Issue by andybeg** [albfan/miraclecast#92] opened 2016-07-11 12:59 UTC
i'm build miraclecast on freescale imx6
build wpa_supplicant supported p2p and wifi-display(config attached)
[config.txt](https://github.com/albfan/miraclecast/files/357095/config.txt)
but get error 

> WARNING: cannot read hostname from systemd.hostname1: Connection timed out (manager_read_name() in ../../../src/wifi/wifid.c:373)
> ERROR: link: invalid arguments (link_set_friendly_name() in ../../../src/wifi/wifid-link.c:190)
> iwlwifi 0000:01:00.0: L1 Disabled - LTR Disabled
> iwlwifi 0000:01:00.0: L1 Disabled - LTR Disabled
> IPv6: ADDRCONF(NETDEV_UP): wlp1s0: link is not ready
> WARNING: supplicant: wpa_supplicant or driver does not support P2P (supplicant_status_fn() in ../../../src/wifi/wifid-supplicant.c:1677)
> WARNING: supplicant: wpa_supplicant does not support wifi-display (supplicant_status_fn() in ../../../src/wifi/wifid-supplicant.c:1768)

PS: i use this WiFi card and its driver in similar project and it work for me 
https://github.com/01org/wds 
my wifi card is intel 7260HM

**Comment by albfan** [comment] 2016-07-11 13:45
Is this your hardware?

https://www.toradex.com/computer-on-modules/nxp-freescale-i.mx

What OS is it using? 

https://en.wikipedia.org/wiki/I.MX#Linux

Miraclecast is succesfully tested (but unstable) on recent archarm on raspberry pi 3.

miraclecast interacts with wifi card by dbus so you need to recompile systemd if you are under 220 version and wpa_supplicant has a lot of improvements in it's dbus interface, see changelog

https://w1.fi/cgit/hostap/plain/wpa_supplicant/ChangeLog

Maybe you're interested on #3 to avoid the dbus dependency

**Comment by andybeg** [comment] 2016-07-11 14:01
my hardware is
http://www.nxp.com/products/software-and-tools/hardware-development-tools/sabre-development-system/sabre-for-automotive-infotainment-based-on-the-i.mx-6-series:RDIMX6SABREAUTO
i'm using linux from yocto and compile systemd 225 using toolchain

I will read about dbus tomorrow, thanks for the quick response

**Comment by albfan** [comment] 2016-07-11 14:22
225, then you have dbus enabled by default.

Check this doc https://wireless.wiki.kernel.org/en/users/drivers/iwlwifi.

See you need to use iwlmvm to have p2p.

http://askubuntu.com/questions/618283/is-iwlwifi-or-iwldvm-or-wext-the-wireless-driver

**Comment by andybeg** [comment] 2016-07-12 05:06
i checked my module configuration and found that iwlmvm module installed and already loaded :(
> # lsmod
> Module                  Size  Used by
> adv7180_tvin           11103  0
> mxc_v4l2_capture       25109  1
> ipu_bg_overlay_sdc      5242  1 mxc_v4l2_capture
> ipu_still               2312  1 mxc_v4l2_capture
> ipu_prp_enc             5872  1 mxc_v4l2_capture
> ipu_csi_enc             3743  1 mxc_v4l2_capture
> ipu_fg_overlay_sdc      6068  1 mxc_v4l2_capture
> iwlmvm                122248  0
> v4l2_int_device         2913  3 ipu_csi_enc,adv7180_tvin,mxc_v4l2_capture
> mac80211              287526  1 iwlmvm
> iwlwifi                88954  1 iwlmvm
> cfg80211              189318  3 iwlwifi,mac80211,iwlmvm
> mxc_dcic                6543  0
> evbug                   1871  0
> galcore               224968  2

**Comment by andybeg** [comment] 2016-07-12 05:43
i'm realy sorry, i find problem, when i compile wpa_supplicant 2.5 i foget to remove old version 2.4 and ,pehaps , miraclecast use it. Now a bit confused, how i can show my android screen om imx6 device

**Comment by andybeg** [comment] 2016-07-12 05:54
i dont see run command in miracle-wifictl, only
list
select
show
set-friendly-name
p2p-scan
connect
disconnect

**Comment by andybeg** [comment] 2016-07-12 06:08
in miracle-sinkctl 
run  4, but wen connect from android it fail
[ADD] Peer: 2a:...@4
[PROV] Peer: 2a:...@4 Type: pbc PIN:
[GO NEG]  Peer: 2a:...@4 Type: pbc PIN:
[FAIL] Peer: 2a:...@4 Reason: unknown

**Comment by andybeg** [comment] 2016-07-12 06:10
interecting thing - my phone mac addres start from 28:... but miracle-sinkctl show it like 2a:...

**Comment by albfan** [comment] 2016-07-12 08:20
There's a bunch of mac addresses on a phone. using a terminal app or adb you can run `netcfg` and see them. I see at least wlan0, p2p0, sit0 and lo UP and rmnet_smux1, rmnet_smux0, dummy0, rmnet_usb1 and rmnet_usb1 DOWN, each one with different mac addresses.

if you run `miracle-wifid` and `miracle-sinkctl` with trace log `--log-level trace` you can see where the problem is. Using [journalctl](https://www.digitalocean.com/community/tutorials/how-to-use-journalctl-to-view-and-manipulate-systemd-logs) you can see driver and spawned process log.  `sudo journalctl -f | grep miracle` should be enough in most cases.

Post here if you get puzzled with output.

I guess **running on freescale imx6 + Yocto** would be a better description for this issue, helping others to find support.

**Comment by andybeg** [comment] 2016-07-12 09:13
when i connect to miraclecast from android device get this error
> IPv6: ADDRCONF(NETDEV_UP): p2p-wlp1s0-0: link is not ready
> IPv6: ADDRCONF(NETDEV_UP): p2p-wlp1s0-0: link is not ready
> IPv6: ADDRCONF(NETDEV_CHANGE): p2p-wlp1s0-0: link becomes ready
> iwlwifi 0000:01:00.0: Time Event end notification failure
> ERROR: supplicant: HUP on dhcp-comm socket on p2p-wlp1s0-0 (supplicant_group_comm_fn() in ../../../src/wifi/wifid-supplicant.c:246)

**Comment by andybeg** [comment] 2016-07-12 09:26
get this log when start 
> miracle-wifid --log-level trace 
and connect from android
[miracle.txt](https://github.com/albfan/miraclecast/files/358969/miracle.txt)

**Comment by albfan** [comment] 2016-07-12 10:21
I see something interesting:

<pre>
TRACE: wpa: raw message: IFNAME=p2p-wlp1s0-2 <3>WPS-REG-SUCCESS 2a:c6:71:01:30:88 4c421baf-ed4b-51c4-91ab-d1bbe7979f17
TRACE: wpa: raw message: <3>P2P-GROUP-FORMATION-SUCCESS 
TRACE: wpa: raw message: <3>P2P-GROUP-FORMATION-SUCCESS 
TRACE: wpa: raw message: <3>P2P-GROUP-STARTED p2p-wlp1s0-2 GO ssid="DIRECT-So" freq=2462 passphrase="embn35a5" go_dev_addr=7c:5c:f8:92:c7:0b
TRACE: wpa: raw message: <3>P2P-GROUP-STARTED p2p-wlp1s0-2 GO ssid="DIRECT-So" freq=2462 passphrase="embn35a5" go_dev_addr=7c:5c:f8:92:c7:0b
DEBUG: supplicant: ssid: DIRECT-So (supplicant_event_p2p_group_started() in ../../../src/wifi/wifid-supplicant.c:1215)
DEBUG: supplicant: new group: p2p-wlp1s0-2 (supplicant_group_new() in ../../../src/wifi/wifid-supplicant.c:484)
DEBUG: supplicant: start local group on new group p2p-wlp1s0-2 as GO/1 (supplicant_event_p2p_group_started() in ../../../src/wifi/wifid-supplicant.c:1250)
TRACE: wpa: raw message: IFNAME=p2p-wlp1s0-2 <3>WPS-PBC-DISABLE 
TRACE: wpa: raw message: IFNAME=p2p-wlp1s0-2 <3>WPS-SUCCESS 
TRACE: wpa: raw message: IFNAME=p2p-wlp1s0-2 <3>CTRL-EVENT-EAP-FAILURE 2a:c6:71:01:30:88
ERROR: supplicant: HUP on dhcp-comm socket on p2p-wlp1s0-2 (supplicant_group_comm_fn() in ../../../src/wifi/wifid-supplicant.c:246)
</pre>

Seems you have PBC disabled and need to connect via WPS.

CTRL-EVENT-EAP-FAILURE says you are not providing a correct passphrase, (that's correct as miraclecast tries to connect via PBC)

I need to dig in the code, to show you the hints to solve this. Are you just a final user or are you ok with change some code to make this work? It shouldn't by complex to solve.

On your side, check if PBC is disabled and if it's possible to enable it to confirm this.

**Comment by andybeg** [comment] 2016-07-12 10:26
i can change code to make this work.
unfortunately I do not fully understand where to check the PBC :(

**Comment by albfan** [comment] 2016-07-12 10:59
Ok, perfect. Meanwhile, detecting method to do a succesful conection could be handy. Check #79 for a test with `wpa_supplicant` and `wpa_cli` doing a p2p by hand. I guess you need to provide different p2p_connect options.

If wds works for you, can you posts its logs or check code about where things go wrong on miraclecast? 

Just curious, why are you checking miraclecast?, is it for UIBC support?, in fact config the connection method is a long wanted feature.

**Comment by andybeg** [comment] 2016-07-12 12:09
it seems that connection from imx6 to android by hand go fine

> root@imx6qsabreauto:~# cat wpa.conf 
> ctrl_interface=DIR=/run/wpa_supplicant GROUP=wheel
> device_name=archlinux-alberto
> device_type=1-0050F204-1
> config_methods=pbc
> driver_param=p2p_device=1
> ap_scan=1
> update_config=1
> root@imx6qsabreauto:~# wpa_supplicant -d -Dnl80211 -c wpa.conf -iwlp1s0 -B                                                                                                                               
> wpa_supplicant v2.5
> random: Trying to read entropy from /dev/random
> Successfully initialized wpa_supplicant
> Initializing interface 'wlp1s0' conf 'wpa.conf' driver 'nl80211' ctrl_interface 'N/A' bridge 'N/A'
> Configuration file 'wpa.conf' -> '/home/root/wpa.coniwlwifi 0000:01:00.0: L1 Disabled - LTR Disabled
> f'
> Reading configuration file '/iwlwifi 0000:01:00.0: L1 Disabled - LTR Disabled
> home/root/wpa.conf'
> ctrl_interface='DIR=/run/wpa_supplicant GROUP=wheel'
> device_name='archlinux-alberto'
> config_methods='pbc'
> driver_param='p2p_device=1'
> ap_scan=1
> update_config=1
> rfkill: Cannot open RFKILL control device
> nl80211: RFKILL status not available
> nl80211: Supported cipher 00-0f-ac:1
> nl80211: Supported cipher 00-0f-ac:5
> nl80211: SIPv6: ADDRCONF(NETDEV_UP): wlp1s0: link is not ready
> upported cipher 00-0f-ac:2
> nl80211: Supported cipher 00-0f-ac:4
> nl80211: Supported cipher 00-0f-ac:6
> nl80211: Using driver-based off-channel TX
> nl80211: Use separate P2P group interface (driver advertised support)
> nl80211: use P2P_DEVICE support
> nl80211: interface wlp1s0 in phy phy0
> nl80211: Set mode ifindex 4 iftype 2 (STATION)
> nl80211: Subscribe to mgmt frames with non-AP handle 0x1c5b5e0
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c5b5e0 match=040a
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c5b5e0 match=040b
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c5b5e0 match=040c
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c5b5e0 match=040d
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c5b5e0 match=090a
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c5b5e0 match=090b
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c5b5e0 match=090c
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c5b5e0 match=090d
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c5b5e0 match=0409506f9a09
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c5b5e0 match=7f506f9a09
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c5b5e0 match=06
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c5b5e0 match=0a07
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c5b5e0 match=0a11
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c5b5e0 match=1101
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c5b5e0 match=1102
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c5b5e0 match=0505
> netlink: Operstate: ifindex=4 linkmode=1 (userspace-control), operstate=5 (IF_OPER_DORMANT)
> nl80211: driver param='p2p_device=1'
> Add interface wlp1s0 to a new radio phy0
> nl80211: Regulatory information - country=00
> nl80211: 2402-2472 @ 40 MHz 20 mBm
> nl80211: 2457-2482 @ 40 MHz 20 mBm (no IR)
> nl80211: 2474-2494 @ 20 MHz 20 mBm (no OFDM) (no IR)
> nl80211: 5170-5250 @ 160 MHz 20 mBm (no IR)
> nl80211: 5250-5330 @ 160 MHz 20 mBm (DFS) (no IR)
> nl80211: 5490-5730 @ 160 MHz 20 mBm (DFS) (no IR)
> nl80211: Added 802.11b mode based on 802.11g information
> wlp1s0: Own MAC address: 7c:5c:f8:92:c7:0a
> wpa_driver_nl80211_set_key: ifindex=4 (wlp1s0) alg=0 addr=(nil) key_idx=0 set_tx=0 seq_len=0 key_len=0
> wpa_driver_nl80211_set_key: ifindex=4 (wlp1s0) alg=0 addr=(nil) key_idx=1 set_tx=0 seq_len=0 key_len=0
> wpa_driver_nl80211_set_key: ifindex=4 (wlp1s0) alg=0 addr=(nil) key_idx=2 set_tx=0 seq_len=0 key_len=0
> wpa_driver_nl80211_set_key: ifindex=4 (wlp1s0) alg=0 addr=(nil) key_idx=3 set_tx=0 seq_len=0 key_len=0
> wlp1s0: RSN: flushing PMKID list in the driver
> nl80211: Flush PMKIDs
> wlp1s0: State: DISCONNECTED -> INACTIVE
> wlp1s0: WPS: UUID based on MAC address: 9d66bce0-2780-5175-a78d-2b9813986c36
> ENGINE: Loading dynamic engine
> ENGINE: Loading dynamic engine
> EAPOL: SUPP_PAE entering state DISCONNECTED
> EAPOL: Supplicant port status: Unauthorized
> nl80211: Skip set_supp_port(unauthorized) while not associated
> EAPOL: KEY_RX entering state NO_KEY_RECEIVE
> EAPOL: SUPP_BE entering state INITIALIZE
> EAP: EAP entering state DISABLED
> ctrl_interface_group=991 (from group name 'wheel')
> wlp1s0: Added interface wlp1s0
> wlp1s0: State: INACTIVE -> DISCONNECTED
> nl80211: Set wlp1s0 operstate 0->0 (DORMANT)
> netlink: Operstate: ifindex=4 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
> nl80211: Create interface iftype 10 (P2P_DEVICE)
> nl80211: New P2P Device interface p2p-dev-wlp1s0 (0x2) created
> Initializing interface 'p2p-dev-wlp1s0' conf '/home/root/wpa.conf' driver 'nl80211' ctrl_interface 'DIR=/run/wpa_supplicant GROUP=wheel' bridge 'N/A'
> Configuration file '/home/root/wpa.conf' -> '/home/root/wpa.conf'
> Reading configuration file '/home/root/wpa.conf'
> ctrl_interface='DIR=/run/wpa_supplicant GROUP=wheel'
> device_name='archlinux-alberto'
> config_methods='pbc'
> driver_param='p2p_device=1'
> ap_scan=1
> update_config=1
> rfkill: Cannot open RFKILL control device
> nl80211: RFKILL status not available
> Could not read interface p2p-dev-wlp1s0 flags: No such device
> nl80211: Supported cipher 00-0f-ac:1
> nl80211: Supported cipher 00-0f-ac:5
> nl80211: Supported cipher 00-0f-ac:2
> nl80211: Supported cipher 00-0f-ac:4
> nl80211: Supported cipher 00-0f-ac:6
> nl80211: Using driver-based off-channel TX
> nl80211: Use separate P2P group interface (driver advertised support)
> nl80211: use P2P_DEVICE support
> nl80211: interface p2p-dev-wlp1s0 in phy phy0
> nl80211: Set mode ifindex 0 iftype 10 (P2P_DEVICE)
> nl80211: Failed to set interface 0 to mode 10: -22 (Invalid argument)
> nl80211: Subscribe to mgmt frames with non-AP handle 0x1c6d8f0
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c6d8f0 match=040a
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c6d8f0 match=040b
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c6d8f0 match=040c
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c6d8f0 match=040d
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c6d8f0 match=090a
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c6d8f0 match=090b
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c6d8f0 match=090c
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c6d8f0 match=090d
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c6d8f0 match=0409506f9a09
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c6d8f0 match=7f506f9a09
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c6d8f0 match=06
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c6d8f0 match=0a07
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c6d8f0 match=0a11
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c6d8f0 match=1101
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c6d8f0 match=1102
> nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x1c6d8f0 match=0505
> nl80211: Start P2P Device p2p-dev-wlp1s0 (0x2): Success
> nl80211: driver param='p2p_device=1'
> Add interface p2p-dev-wlp1s0 to existing radio phy0
> nl80211: Regulatory information - country=00
> nl80211: 2402-2472 @ 40 MHz 20 mBm
> nl80211: 2457-2482 @ 40 MHz 20 mBm (no IR)
> nl80211: 2474-2494 @ 20 MHz 20 mBm (no OFDM) (no IR)
> nl80211: 5170-5250 @ 160 MHz 20 mBm (no IR)
> nl80211: 5250-5330 @ 160 MHz 20 mBm (DFS) (no IR)
> nl80211: 5490-5730 @ 160 MHz 20 mBm (DFS) (no IR)
> nl80211: Added 802.11b mode based on 802.11g information
> p2p-dev-wlp1s0: Own MAC address: 7c:5c:f8:92:c7:0b
> p2p-dev-wlp1s0: RSN: flushing PMKID list in the driver
> nl80211: Flush PMKIDs
> p2p-dev-wlp1s0: State: DISCONNECTED -> INACTIVE
> p2p-dev-wlp1s0: WPS: UUID from the first interface: 9d66bce0-2780-5175-a78d-2b9813986c36
> ENGINE: Loading dynamic engine
> ENGINE: Loading dynamic engine
> EAPOL: SUPP_PAE entering state DISCONNECTED
> EAPOL: Supplicant port status: Unauthorized
> nl80211: Skip set_supp_port(unauthorized) while not associated
> EAPOL: KEY_RX entering state NO_KEY_RECEIVE
> EAPOL: SUPP_BE entering state INITIALIZE
> EAP: EAP entering state DISABLED
> Using existing control interface directory.
> ctrl_interface_group=991 (from group name 'wheel')
> P2P: Add operating class 81
> P2P: Channels - hexdump(len=11): 01 02 03 04 05 06 07 08 09 0a 0b
> P2P: Own listen channel: 81:1
> P2P: Random operating channel: 81:6
> P2P: initialized
> P2P: channels: 81:1,2,3,4,5,6,7,8,9,10,11
> P2P: cli_channels:
> p2p-dev-wlp1s0: Added interface p2p-dev-wlp1s0
> p2p-dev-wlp1s0: State: INACTIVE -> DISCONNECTED
> nl80211: Set p2p-dev-wlp1s0 operstate 0->0 (DORMANT)
> netlink: Operstate: ifindex=0 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
> p2p-dev-wlp1s0: Determining shared radio frequencies (max len 1)
> p2p-dev-wlp1s0: Shared frequencies (len=0): completed iteration
> P2P: Add operating class 81
> P2P: Channels - hexdump(len=11): 01 02 03 04 05 06 07 08 09 0a 0b
> P2P: Update channel list
> P2P: channels: 81:1,2,3,4,5,6,7,8,9,10,11
> P2P: cli_channels:
> Daemonize..
> root@imx6qsabreauto:~# imx-sdma 20ec000.sdma: firmware not found
> 
> root@imx6qsabreauto:~# wpa_cli
> wpa_cli v2.5
> Copyright (c) 2004-2015, Jouni Malinen <j@w1.fi> and contributors
> 
> This software may be distributed under the terms of the BSD license.
> See README for more details.
> 
> 
> Selected interface 'p2p-dev-wlp1s0'
> 
> Interactive mode
> 
> > p2p_find
> OK
> <3>CTRL-EVENT-SCAN-STARTED 
> <3>P2P-DEVICE-FOUND 32:cd:a7:af:41:36 p2p_dev_addr=32:cd:a7:af:c1:36 pri_dev_type=10-0050F204-5 name='YotaPhone_664b' config_methods=0x188 dev_capab=0x25 group_capab=0x0 wfd_dev_info=0x00101c440032 ne1
> <3>CTRL-EVENT-SCAN-STARTED 
> > OK
> <3>P2P-FIND-STOPPED 
> p2p_connect 2a:c6:71:01:30:88 pbc
> > OK
> <3>P2P-GO-NEG-SUCCESS role=GO freq=2437 ht40=0 peer_dev=2a:c6:71:01:30:88 peer_iface=2a:c6:71:01IPv6: ADDRCONF(NETDEV_UP): p2p-wlp1s0-0: link is not ready
> :30:88 wps_method=PBC
> IPv6: ADDRCONF(NETDEV_UP): p2p-wlp1s0-0: link is not ready
> IPv6: ADDRCONF(NETDEV_CHANGE): p2p-wlp1s0-0: link becomes ready
> <3>P2P-GROUP-FORMATION-SUCCESS 
> <3>P2P-GROUP-STARTED p2p-wlp1s0-0 GO ssid="DIRECT-Tb" freq=2437 passphrase="sMDuxrMt" go_dev_addr=7c:5c:f8:92:c7:0b
>

**Comment by andybeg** [comment] 2016-07-13 07:32
when i start
miracle-wifid
get ERROR

> # WARNING: cannot read hostname from systemd.hostname1: Activation of org.freedesktop.hostname1 timed out (manager_read_name() in ../../../src/wifi/wifid.c:373)
> ERROR: link: invalid arguments (link_set_friendly_name() in ../../../src/wifi/wifid-link.c:190)
> 

here https://github.com/albfan/miraclecast/issues/70 you write that this happens whem systemd build without kdbus, can i check somehow is kdbus present

**Comment by albfan** [comment] 2016-07-13 12:17
from version 221 systemd has kdbus enabled by default. But you can install d-feet and check if you see if interprocess messages are enabled

**Comment by albfan** [comment] 2016-07-16 14:20
From this line

> ERROR: supplicant: HUP on dhcp-comm socket on p2p-wlp1s0-2 (supplicant_group_comm_fn() in ../../../src/wifi/wifid-supplicant.c:246)

can you post here output from 

    $ sudo journalctl -b -t miracle-dhcp-p2p-wlp1s0-2

see syslog identifier `-t` could change from test to test, it is composed by "miracle-dhcp" and IFNAME value on

> TRACE: wpa: raw message: IFNAME=p2p-wlp1s0-2

Maybe we can see why dhcp is been killed.

**Comment by albfan** [comment] 2016-11-18 04:10
Any progress on this? can I close the issue?

**Comment by Bwavex** [comment] 2017-03-16 08:01
Hi！albfan. My situation is same as this！I use IMX6q +yocto. systemd is 226 . My wifi dongle is marvell 8897. 
WARNING: cannot read hostname from systemd.hostname1: The name org.freedesktop.hostname1 was not provided by any .service files (manager_read_name() )
ERROR: link: invalid arguments (link_set_friendly_name() )

**Comment by albfan** [comment] 2017-04-18 04:04
check https://github.com/OSSystems/meta-miracast/tree/master/recipes-miracast/miraclecast. Is a yocto recipe and it's working!

**Closed by albfan** 2017-04-18 04:04 UTC
